"""The titles of the shipped workflows' groups, subgraphs, notes and nodes."""

SHARED_TEXTS = {
    "start": "Start Here",
    "note": "Note",
    "input": "Input",
    "write": "Write",
    "check": "Check",
    "caption": "Caption",
    "draw": "Draw",
    "choose": "Choose",
    "inspect": "Inspect",
    "ideas": "Ideas",
    "edit": "Edit",
    "prompts": "Prompts",
    "vector": "Vector",
    "sticker": "Sticker",
    "frame": "Frame",
    "move": "Move",
    "animate": "Animate",
    "recover": "Recover",
    "transcribe": "Transcribe",
    "triage": "Triage",
    "reply": "Reply",
    "translate": "Translate",
    "speak": "Speak",
    "search": "Search",
    "answer": "Answer",
    "rank": "Rank",
    "escalate": "Escalate",
    "front": "Front",
    "detail": "Detail",
    "listing": "Listing",
    "facts": "Facts",
    "summary": "Summary",
    "approved": "Approved",
    "review": "Review",
    "rejected": "Rejected",
    "brief": "Brief",
    "subject": "Subject",
    "campaign": "Campaign",
    "brand": "Brand",
    "idea": "Idea",
    "prompt": "Prompt",
    "mask": "Mask",
    "clean": "Clean",
    "distorted": "Distorted",
    "language": "Language",
    "notes": "Notes",
    "question": "Question",
    "articles": "Articles",
}

__all__ = ["SHARED_TEXTS"]
