"""Units the size and time limits are written in."""

BYTES_PER_MEBIBYTE = 1_048_576

SECONDS_PER_MINUTE = 60

MINUTES_PER_HOUR = 60

MILLISECONDS_PER_SECOND = 1000

__all__ = [
    "BYTES_PER_MEBIBYTE",
    "MILLISECONDS_PER_SECOND",
    "MINUTES_PER_HOUR",
    "SECONDS_PER_MINUTE",
]
